version: '3.4'
services:
  api:
    image: go-unchained-local
    environment:
      - GOCACHE=/tmp
    build:
      context: ../../build
      dockerfile: Dockerfile.local
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.binance-api.rule=Host(`api.binance.localhost`)'
      - 'traefik.http.services.binance-api.loadbalancer.server.port=3000'
    command: ["-r", "(pkg|internal|binance)", "-R", "swagger", "--", "sh", "-c", "swagger generate spec -w coinstacks/binance -o coinstacks/binance/api/swagger.json -x protoc-gen-openapiv2 -m && go run cmd/binance/main.go -env cmd/binance/.env"]
    working_dir: /app
    volumes:
      - ../..:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    networks:
      - binance

networks:
  binance:
    name: binance_default
    external: true