version: '3.8'

services:
  api:
    image: unchained-local-node
    env_file: .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.arbitrum-api.rule=Host(`api.arbitrum.localhost`)'
      - 'traefik.http.services.arbitrum-api.loadbalancer.server.port=3000'
    working_dir: /app/node/coinstacks/arbitrum/api
    command: yarn nodemon
    volumes:
      - ../../..:/app
    networks:
      - arbitrum

networks:
  arbitrum:
    name: arbitrum_default
    external: true
